title: "Aishani Pathak"
description: "Machine Learning • TDA • Robotics • Computer Vision"
theme: null
markdown: kramdown
plugins:
  - jekyll-feed

# Navigation bar
navbar:
  - name: "Home"
    link: "/"
  - name: "Research"
    link: "/research"
  - name: "Publications"
    link: "/publications"

